== Abstract


This thesis investigates the integration of Finite Element Analysis (FEA) and Multi-Body Dynamics (MBD) to create a robust simulation framework for flexible multi-body systems experiencing dynamic interactions. While traditional MBD methods are effective for simulating large, rigid-body motions, they often fail to capture the nuanced deformations of flexible components, a gap that FEA can fill. However, the independent use of each method limits the accuracy of simulations in scenarios requiring an understanding of both rigid and flexible dynamics. This research addresses this limitation by presenting a coupled FEA-MBD approach that enables seamless interaction between flexible and rigid components, specifically applied to a slider-crank mechanism.

The coupling strategy utilizes a co-simulation technique, wherein deformation data from FEA and motion data from MBD are exchanged iteratively to achieve dynamic fidelity. Key challenges in mesh updating, solver synchronization, and time-stepping coordination between the FEA and MBD domains are addressed. The method’s validity is demonstrated through a case study on a slider-crank mechanism, a system where complex interactions between flexibility and motion are critical. Results from this study illustrate the improved accuracy and computational efficiency of the coupled FEA-MBD approach over conventional methods. The findings underscore the framework’s applicability in engineering contexts requiring precise modeling of flexible structures undergoing dynamic loads, with implications for robotics, automotive engineering, and biomechanical systems. This thesis thus contributes to advancing multi-body simulations, enabling broader applications of FEA-MBD coupling in engineering and research.

== Motivation 

In the realm of mechanical and structural engineering, accurately predicting the behavior of complex systems under dynamic loads is a fundamental requirement. Traditional analysis methods—Finite Element Analysis (FEA) and Multi-Body Dynamics (MBD)—each offer significant insights into system behavior but also have inherent limitations when used independently. MBD focuses on the motion and interaction of rigid bodies, providing an efficient means to model large-scale mechanical systems with interconnected components. However, MBD treats all bodies as rigid, which limits its capacity to capture the flexible deformations that can occur under load, especially in components experiencing high stresses, vibration, or structural flexibility.

Conversely, FEA is well-suited for modeling stress, strain, and deformation in flexible structures. By discretizing a structure into finite elements, FEA can resolve complex deformations and stress distributions with high accuracy. Yet, when applied to systems with significant rigid-body motion, FEA becomes computationally intensive and less effective in capturing the kinematic constraints and interactions between interconnected bodies in motion. Therefore, solely using FEA for systems involving significant rigid motion is computationally prohibitive and challenging to implement effectively.

Coupling FEA with MBD allows for a hybrid approach that leverages the strengths of both methodologies. In a coupled FEA-MBD model, the FEA provides the detailed deformation behavior of flexible components, while the MBD handles the large-scale motion and kinematic interactions of rigid components. This integrated approach is particularly crucial for systems where flexible bodies undergo substantial deformation while interacting dynamically with other rigid parts, such as in the case of a slider-crank mechanism. In such mechanisms, where the dynamic response depends not only on the motion of individual parts but also on the flexibility of components like the connecting rod, coupling provides an enhanced and realistic simulation of operational conditions.

The need for FEA-MBD coupling is further underscored in applications across robotics, biomechanics, and automotive engineering, where structures frequently experience both rigid-body motion and localized deformations. By enabling more accurate simulations, this coupled approach aids in designing systems that can withstand dynamic loads, enhances predictive maintenance strategies by providing better insight into stress points, and facilitates the optimization of components for performance and durability. In sum, FEA-MBD coupling is essential for advancing the fidelity of simulations in engineering applications where the interplay of flexibility and motion significantly impacts system performance.